server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: frontend-service
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
  
# Eureka configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# API Gateway configuration
gateway:
  base-url: http://localhost:8765
  api-key: frontend-service-key-2024

# Logging configuration
logging:
  level:
    com.log430.tp5: INFO
    org.springframework.cloud: INFO
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %level - %msg%n"
