# =============================================
# Docker Compose - Usage Instructions
#
# Install Docker Compose (if needed):
# sudo apt install docker-compose
#
# To build the image:
# docker-compose build
#
# To run the application:
# docker-compose up
#
# To run in detached mode:
# docker-compose up -d
#
# To view container logs:
# docker-compose logs -f
# =============================================

version: "3.8"

services:
  java-app:
    container_name: java-hello-app
    build:
      context: ./java-hello-world
      dockerfile: Dockerfile
    image: java-hello-app
    ports:
      - "8080:8080"      # Permet l'accès au serveur lorsqu'il est actif dans l'application
    restart: unless-stopped
    stdin_open: true     # Permet l’interaction terminal
    tty: true            # Évite la fermeture immédiate du conteneur
