# =============================================
# Docker Compose - Usage Instructions
#
# Install Docker Compose (if needed):
# sudo apt install docker-compose
#
# To build the image:
# docker-compose build
#
# To run the application:
# docker-compose up
#
# To run in detached mode:
# docker-compose up -d
#
# To view container logs:
# docker-compose logs -f
# =============================================

version: "3.8"

services:
  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: magasin
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - magasin-net
    restart: unless-stopped
  java-app:
    container_name: magasin-app
    build:
      context: ./magasin
      dockerfile: Dockerfile
    image: magasin-app
    depends_on:
      - db
    networks:
      - magasin-net
    restart: unless-stopped
    stdin_open: true     # Permet l’interaction terminal
    tty: true            # Évite la fermeture immédiate du conteneur

#Permet le stockaged des données de façon persistante dans PostgreSQL
volumes:
  pgdata:
  
networks:
  magasin-net: