@startuml
title Vue d’implémentation – Organisation des modules (MVC + DAO)

package "com.log430.tp1.view" {
  class ConsoleView
}

package "com.log430.tp1.controller" {
  class ConsoleController
}

package "com.log430.tp1.model" {
  class Produit
  class Vente
  class Retour
  class Employe
}

package "com.log430.tp1.dao" {
  class ProduitDAO
  class VenteDAO
  class RetourDAO
}

ConsoleView --> ConsoleController : interagit
ConsoleController --> ProduitDAO
ConsoleController --> VenteDAO
ConsoleController --> RetourDAO
ConsoleController --> Produit
ConsoleController --> Vente
ConsoleController --> Retour

@enduml
