spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://postgres:5432/auditdb}
    username: ${POSTGRES_USER:audituser}
    password: ${POSTGRES_PASSWORD:auditpass}
    
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://discovery-server:8761/eureka/}
